# Generated by Django 5.2.8 on 2026-02-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absent',
            name='response_content',
            field=models.TextField(blank=True),
        ),
    ]
