# Generated by Django 5.2.8 on 2026-02-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0002_alter_absent_response_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absent',
            options={'ordering': ('-create_time',)},
        ),
    ]
